language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
install:
- git describe --tags | cut -c 2- > VERSION
- python setup.py install
- pip install coverage
- pip install python-coveralls
script: py.test 
after_success:
  - coverage combine
  - coveralls
notifications:
  email: true
deploy:
  provider: pypi
  user: mavier
  password:
    secure: Is4yyFIyPi7+L50CZ0KSE8GF37Ag/HHN2uPisOtP4ai/uU3M4j3Ju1AQS2rf7lEEDF4XVnAaf+xa5oLpxPeEmtG+lCXleg/28Tbrmfi7l8GMUVlB5PaF4Yaj4/qjyVGGQil9TxxyNgc94EO/S+7LxY2FmcXpiJK+uRjKuhelY6E=
  on:
    tags: true
    branch: master
